name: Test

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * 3,6'

jobs:
  test:
    strategy:
      matrix:
        svelte: [svelte@2, svelte@3.5.0, svelte@3.6.0, svelte@3.7.0, svelte@3.8.0, svelte@3.9.0, svelte@3.10.0, svelte@3.11.0, svelte@3.12.0, svelte@3.13.0, svelte@3.14.0, svelte@3.15.0, svelte@3.16.0, svelte@3.17.0, svelte@3.18.0, svelte@3.19.0, svelte@3.20.0, svelte@3.21.0, svelte@3.22.0, svelte@latest]
        jest: [jest@latest]
        node: [11.13.0]
        include:		
        - svelte: svelte@latest	
          jest: jest@latest
          node: 12
        - svelte: svelte@latest	
          jest: jest@latest
          node: 13
        - svelte: svelte@latest		
          jest: jest@latest
          node: 14
    env:
      SVELTE_VERSION: ${{ matrix.svelte }}
      JEST_VERSION: ${{ matrix.jest }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: cat package.json && npm i $SVELTE_VERSION $JEST_VERSION --save-dev --no-package-lock && cat package.json && rm -r node_modules && npm i -f
      - run: npm test
