name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 1 * *'

jobs:
  test:
    strategy:
      matrix:
        svelte:
          [
            svelte@2,
            svelte@3.20.0,
            svelte@3.21.0,
            svelte@3.22.0,
            svelte@3.23.0,
            svelte@3.24.0,
            svelte@3.25.0,
            svelte@3.26.0,
            svelte@3.27.0,
            svelte@3.28.0,
            svelte@3.29.0,
            svelte@3.30.0,
            svelte@3.31.0,
            svelte@3.32.0,
            svelte@3.33.0,
            svelte@3.34.0,
            svelte@3.35.0,
            svelte@3.36.0,
            svelte@3.37.0,
            svelte@3.38.0,
            svelte@3.39.0,
            svelte@3.40.0,
            svelte@3.41.0,
            svelte@3.42.0,
            svelte@3.43.0,
            svelte@3.44.0,
            svelte@latest,
          ]
        jest: [jest@25.0.0]
        node: [14]
        include:
          # - svelte: svelte@latest
          #   jest: jest@25.0.0
          #   node: 15
          # - svelte: svelte@latest
          #   jest: jest@25.0.0
          #   node: 16
          - svelte: svelte@latest
            jest: jest@25.0.0
            node: 14
          - svelte: svelte@latest
            jest: jest@26.0.0
            node: 14
          - svelte: svelte@latest
            jest: jest@27.0.0
            node: 14
    env:
      SVELTE_VERSION: ${{ matrix.svelte }}
      JEST_VERSION: ${{ matrix.jest }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm i $SVELTE_VERSION --save-dev && npm i
      - run: npm test
