name: Test

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * 3,6'

jobs:
  test:
    strategy:
      matrix:
        svelte: [svelte@2, svelte@3.20.0, svelte@3.21.0, svelte@3.22.0, svelte@latest]
        jest: [jest@25.0.0]
        node: [11.13.0]
    env:
      SVELTE_VERSION: ${{ matrix.svelte }}
      JEST_VERSION: ${{ matrix.jest }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm i -g $SVELTE_VERSION $JEST_VERSION && npm i
      - run: npm test
